# Site settings
title: Luofan's
motto: 测试座右铭
email: jatfret@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jatfret.github.io" # the base hostname & protocol for your site
twitter_username: jatfret
github_username:  jatfret

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "posts" #一个空字符串代表项目中的所有文件
      type: "posts"
    values:
      layout: "post"
      author: "luofan"
  -
    scope:
      path: "index"
      type: "pages"
    values:
      layout: "index"
  -
    scope:
      path: "/XX/XX"
      type: "xxx"
    values:
      layout: "xxxxxx"


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
#theme: jekyll-theme-cayman
#theme: jekyll-theme-cayman
